### ISSUE TITLE
Loading more images at end of gallery

### ISSUE THREAD

**Issue by Purus** [pedroabreu/ion-gallery#45]
In my application,by default I show 10 images and when I go to the last image, I would like to load additional images from remote server and append to gallery.

How do I know if I have reached the last image of the gallery? Are there any methods available?

Currently I am using Slide-Box of Ionic and it works fine. but I want to replace it with your library.

**Comment by pedroabreu** [comment]
As it is now, I don't think you can. You would probably need to run a function passed trough the scope (Or broadcast an event... not sure which one would be the best approach) and execute it when the last image of the array was loaded on the 3rd slice (Because we would need to render the next image when the last image becomes visible)
From the top of my head, this would be the first thing to try. I'll have a think about this

**Comment by Purus** [comment]
Thanks for response.

I really liked this plugin but due to lack of this functionality I could
not use this.

Is there any possibility to add as part of plugin?

**Comment by pedroabreu** [comment]
You can always try to implement it and then open a PR for merge ;)
